/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

/* tslint:disable */

import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S } from 'capnp-ts';
export const _capnpFileId = "9cbc682922e84ff9";
export class Baz extends __S {
    static readonly _capnp = { displayName: "Baz", id: "f2f28862b8e82db7", size: new __O(0, 1) };
    getBar(): string { return __S.getText(0, this); }
    setBar(value: string): void { __S.setText(0, value, this); }
    toString(): string { return "Baz_" + super.toString(); }
}
capnp.registerSchema(capnp.CodeGeneratorRequest, _capnpFileId, [
    "eJwTiHJgFuTdLizJKC/AyMPGGMjByvZ/u+6LHUkdnz4xCEYy/v/p/0JJM2PPHAZWRnYGBkPHV0yCuUCGYKY9A5IkYzADk2HnKSbBreIMzP/1Q4tT",
    "i4r1s7hSMhOr9FNSy/SzQCxTU0Nj/eTEgrwC3ZJi/YLE5OzE9NRiiEgySKgktbhEPzOvJDW9KLEkMz9PPzO3IL+oRDcpsUgPrIrfyimxKoCRMZCF",
    "mYWBgYUR6A5eJQaGQA5mxkARJkZ2oEJGHgYmIGaknSOA9rEwMiKFEqMSO9BZQEEmRIAYsgIDw5Cdlq4AhgMAMQCRpgAApg=="
]);
