/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

/* tslint:disable */

import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S } from 'capnp-ts';
import { Baz } from './import-bar.capnp';
export const _capnpFileId = "fc552bdafbb0b889";
export class Foo extends __S {
    static readonly _capnp = { displayName: "Foo", id: "f92e265d07c50136", size: new __O(0, 1) };
    adoptBaz(value: capnp.Orphan<Baz>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownBaz(): capnp.Orphan<Baz> { return __S.disown(this.getBaz()); }
    getBaz(): Baz { return __S.getStruct(0, Baz, this); }
    hasBaz(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initBaz(): Baz { return __S.initStructAt(0, Baz, this); }
    setBaz(value: Baz): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    toString(): string { return "Foo_" + super.toString(); }
}
capnp.registerSchema(capnp.CodeGeneratorRequest, _capnpFileId, [
    "eJy1Uz1o1GAYfp8vSa9XelxCCtdFCjdY9LzGcLRDFn8GQcGfVDo4iOTuYr1KkyOJhZ4I6qTdHFxEXF3dPEERBx0KCgou7kJxu04eip9fcrmkgzi1",
    "Q+Dj+548z/M+7/uq309KZqnC9EPSnIrpCdizygQfXtypHrnx+inhMjFzsC2eUSGJL+F94erhhSFpV8Af9l/8+lZb+U0KCkQNBT+YbsZHvY4TBP6y",
    "vtNvPtjdTcAZ4wh8PgZvJuBbCTgjixUbjyEk36Gif8QcMX7vwvH+7Ts/3xCmiOmfcV//inl9kLwdu3b37bPhh1dkqwpyJEEf4ouuMCGxzCQICWMl",
    "dIPQWJtqd5ye0XY3jLX4tLhoNoyW0/W69Sg0uk7rprPqhqObVnwVuWFkdLzIXQ2cqON7Rme96wdRvekECwmKyJaxt15UC6ed3r4LXvf9kWDZOuP7",
    "lwBblmQiGURaqSpcTEqwZxgKTacHNfdDgHqQ9ZctUe1/7QSYJia+/TeRZZI2IZ9Q0QSRkrjcOyMyw6kZCCfi/Rw/63WiwG+7IiGekBitGmopnz0p",
    "6LI/teIy//Ro8GfzeVs0uHiUe866GwqjBLccn/8hNJsKPRmRW5YDz/Oj2L/khUSZJks1rTEpXBFnnFnCmu2GqWwzzZw/0BDjqrMt0opb+eZqpS1u",
    "pJZRG8dEfDwOyPfhL9TpbhQAbhQ="
]);
